# Generated by Django 4.2.6 on 2023-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0003_remove_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gallery_pic', models.ImageField(upload_to='profile_pictures/')),
            ],
        ),
    ]
