# Generated by Django 4.2.4 on 2023-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0006_alter_enrollment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualFitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(max_length=50)),
                ('meeting_link', models.URLField()),
            ],
        ),
    ]
