# Generated by Django 4.2.4 on 2023-11-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0007_virtualfitnessclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualfitnessclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitMate.trainer'),
        ),
    ]
