# Generated by Django 4.2.4 on 2024-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0010_userprofile_suggested_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='due_date',
        ),
    ]
