# Generated by Django 4.2.4 on 2024-02-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0011_remove_enrollment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='price',
        ),
    ]
