# Generated by Django 4.2.4 on 2024-02-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0012_remove_enrollment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
