# Generated by Django 4.2.4 on 2024-02-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0013_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='suggested_workout',
        ),
    ]
