# Generated by Django 4.2.4 on 2024-02-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0015_session_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
