# Generated by Django 4.2.4 on 2024-02-28 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitMate', '0018_workout_bodymeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('workout', 'Workout'), ('body_measurement', 'Body Measurement')], max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='BodyMeasurement',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
